# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build All Projects

# Which actions trigger workflow
on:
  push:
    branches: [ 'main', 'dev' ]
  pull_request:
    branches: [ 'main' ]
  workflow_call:
  workflow_dispatch:

# All builds to test
jobs:
  build-1_12:
    name: Build 1.12

    # Which operating system to test on
    runs-on: ubuntu-latest
    permissions:
      contents: read

    # Sets working directory to the 1.12 Project
    defaults:
      run:
        working-directory: ./1.12

    # Workflow stages
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      # Gradle Setup will crash if wrapper not executable
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      # Attempts to build project
      - name: Build
        run: ./gradlew build

      # Uploads .jar file to GitHub for publishing
      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: jars-1_12
          path: 1.12/build/libs/*.jar
          overwrite: true

  build-1_16:
    name: Build 1.16

    # Which operating system to test on
    runs-on: ubuntu-latest
    permissions:
      contents: read

    # Sets working directory to the 1.16 Project
    defaults:
      run:
        working-directory: ./1.16

    # Workflow stages
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      # Gradle Setup will crash if wrapper not executable
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      # Attempts to build project
      - name: Download Assets
        run: ./gradlew downloadAssets

      - name: Run Forge Datagen
        run: ./gradlew forge:runDatagen

      - name: Build Fabric
        run: ./gradlew fabric:build

      - name: Build Forge
        run: ./gradlew forge:build

      - name: Merge Jars
        run: ./gradlew mergeJars

      # Uploads .jar file to GitHub for publishing
      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: jars-1_16
          path: 1.16/build/forgix/*.jar
          overwrite: true

  build-1_18:
    name: Build 1.18

    # Which operating system to test on
    runs-on: ubuntu-latest
    permissions:
      contents: read

    # Sets working directory to the 1.18 Project
    defaults:
      run:
        working-directory: ./1.18

    # Workflow stages
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      # Gradle Setup will crash if wrapper not executable
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      # Attempts to build project
      - name: Download Assets
        run: ./gradlew downloadAssets

      - name: Run Fabric Datagen
        run: ./gradlew fabric:runDatagen

      - name: Run Forge Datagen
        run: ./gradlew forge:runDatagen

      - name: Build Fabric
        run: ./gradlew fabric:build

      - name: Build Forge
        run: ./gradlew forge:build

      - name: Merge Jars
        run: ./gradlew mergeJars

      # Uploads .jar file to GitHub for publishing
      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: jars-1_18
          path: 1.18/build/forgix/*.jar
          overwrite: true

  build-1_19:
    name: Build 1.19

    # Which operating system to test on
    runs-on: ubuntu-latest
    permissions:
      contents: read

    # Sets working directory to the 1.19 Project
    defaults:
      run:
        working-directory: ./1.19

    # Workflow stages
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      # Gradle Setup will crash if wrapper not executable
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      # Attempts to build project
      - name: Download Assets
        run: ./gradlew downloadAssets

      - name: Run Fabric Datagen
        run: ./gradlew fabric:runDatagen

      - name: Run Forge Datagen
        run: ./gradlew forge:runDatagen

      - name: Build Fabric
        run: ./gradlew fabric:build

      - name: Build Forge
        run: ./gradlew forge:build

      - name: Merge Jars
        run: ./gradlew mergeJars

      # Uploads .jar file to GitHub for publishing
      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: jars-1_19
          path: 1.19/build/forgix/*.jar
          overwrite: true

  build-1_20:
    name: Build 1.20

    # Which operating system to test on
    runs-on: ubuntu-latest
    permissions:
      contents: read

    # Sets working directory to the 1.20 Project
    defaults:
      run:
        working-directory: ./1.20

    # Workflow stages
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      # Gradle Setup will crash if wrapper not executable
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      # Attempts to build project
      - name: Download Assets
        run: ./gradlew downloadAssets

      - name: Run Fabric Datagen
        run: ./gradlew fabric:runDatagen

      - name: Run Forge Datagen
        run: ./gradlew forge:runDatagen

      - name: Build Fabric
        run: ./gradlew fabric:build

      - name: Build Forge
        run: ./gradlew forge:build

      - name: Merge Jars
        run: ./gradlew mergeJars

      # Uploads .jar file to GitHub for publishing
      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: jars-1_20
          path: 1.20/build/forgix/*.jar
          overwrite: true

  build-1_21:
    name: Build 1.21

    # Which operating system to test on
    runs-on: ubuntu-latest
    permissions:
      contents: read

    # Sets working directory to the 1.21 Project
    defaults:
      run:
        working-directory: ./1.21

    # Workflow stages
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      # Gradle Setup will crash if wrapper not executable
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      # Attempts to build project
      - name: Download Assets
        run: ./gradlew downloadAssets

      - name: Run Fabric Datagen
        run: ./gradlew fabric:runDatagen

      - name: Run NeoForge Datagen
        run: ./gradlew neoforge:runDatagen

      - name: Build Fabric
        run: ./gradlew fabric:build

      - name: Build NeoForge
        run: ./gradlew neoforge:build

      - name: Merge Jars
        run: ./gradlew mergeJars

      # Uploads .jar file to GitHub for publishing
      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: jars-1_21
          path: 1.21/build/forgix/*.jar
          overwrite: true